ALTER TABLE jobs
  ADD COLUMN max_attempts INT NOT NULL DEFAULT 5,
  ADD COLUMN attempt_count INT NOT NULL DEFAULT 0,
  ADD COLUMN initial_delay_ms INT NOT NULL DEFAULT 1000,
  ADD COLUMN backoff_multiplier DOUBLE PRECISION NOT NULL DEFAULT 2.0,
  ADD COLUMN max_delay_ms INT NOT NULL DEFAULT 60000,
  ADD COLUMN jitter DOUBLE PRECISION NOT NULL DEFAULT 0.1,
  ADD COLUMN next_run_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX jobs_state_next_run_at_idx ON jobs (state, next_run_at);
